channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=23.1.2
- pip:
  - mlflow==2.3
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - psutil==5.9.0
  - scikit-learn==1.2.0
  - scipy==1.9.3
name: mlflow-env
